Add dto class, add mapstruct and mappers, add BookController(with methods), create custom exception and remove CommandLineRunner
Extase67/BookShop pull request #2
Opened 2024-12-21 16:48 UTC by Extase67

Add BookDto.class as a response DTO, and CreateBookRequestDto.class as a request DTO
Add Mapstruct and mappers
Return and accept DTOs on the service layer
Add BookController with methods:
public List getAll()
public BookDto getBookById(Long id)
public BookDto createBook(CreateBookRequestDto bookDto) Add missing methods in the BookService and BookRepository Create and use EntityNotFoundException class
Remove CommandLineRunner bean

2024-12-21 17:00 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2024-12-21 17:00 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
Duplicated starter

2024-12-21 17:00 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/controller/BookController.java
> +
```suggestion
```

2024-12-21 17:00 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/dto/CreateBookRequestDto.java
> +    private Long id;
Should you provide the id in the request dto?

2024-12-21 17:00 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/service/BookServiceImpl.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-12-21 17:00 UTC, liliia-ponomarenko commented on pom.xml
> +</project>
add one empty line

2024-12-21 20:22 UTC, sarakhmen requested changes
Let's slightly improve your solution :)

2024-12-21 20:22 UTC, sarakhmen commented on src/main/java/com/example/demo/repository/BookRepositoryImpl.java
> +            return Optional.ofNullable(book);
do we really need this book variable? please inline

2024-12-21 20:22 UTC, sarakhmen commented on src/main/java/com/example/demo/service/BookServiceImpl.java
> +        return bookMapper.toDto(book);
optional has map() method. please use to chain toDto() method call

2024-12-21 20:22 UTC, sarakhmen commented on src/main/java/com/example/demo/service/BookServiceImpl.java
> +                .toList();
Is it possible to set up your mapper to map a list of entities to a list of entities? Instead of using streams and map each item one by one?

2024-12-22 15:09 UTC, sarakhmen approved these changes
great job!

2024-12-22 17:09 UTC, merged