Pagination sorting swagger
Extase67/BookShop pull request #6
Opened 2024-12-29 13:25 UTC by Extase67

2024-12-29 15:46 UTC, Elena-Bruyako requested changes
see comments

2024-12-29 15:46 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/controller/BookController.java
>      public BookDto update(@PathVariable Long id, @RequestBody CreateBookRequestDto bookDto) {
```suggestion
    public BookDto update(@PathVariable Long id, @RequestBody @Valid CreateBookRequestDto bookDto) {
```

2024-12-29 15:46 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/dto/CreateBookRequestDto.java
> +    @Positive
```suggestion
    @Positive
    @NotNull
```

2024-12-30 10:45 UTC, liliia-ponomarenko approved these changes
Good job! A few recommendations ;)

2024-12-30 10:45 UTC, liliia-ponomarenko commented on pom.xml
> +            <artifactId>hibernate-validator</artifactId>
better use spring-boot-starter-validation

2024-12-30 10:45 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/controller/BookController.java
> +    public List<BookDto> findAll(Pageable pageable) {
better return Page instead of a List

2024-12-30 17:52 UTC, merged